language: node_js
node_js:
    - "16"
cache: npm

install:
    - npm install

script:
    - npm run build

deploy:
    provider: pages
    github-token: $GITHUB_TOKEN
    local_dir: build 
    on:
        branch: main