language: node_js
node_js:
  - '16'

branches:
  only:
    - main

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main