language: node_js
node_js:
  - 19

branches:
  only:
  - main
cache:
  directories:
  - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  #- yarn lint
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
