language: node_js
node_js:
  - '16'

branches:
  only:
    - main

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  keep_history: true
  on:
    branch: main