name: DevOps Lab Exercise
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
# Controls when the workflow will run

language: node_js
node_js:
  - "20.x"

branches:
  only:
  - main
cache:
  directories:
  - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  #- yarn lint
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build

on:
  branch: master
